name: Auto Update VexonHub Key

on:
  schedule:
    - cron: '0 */12 * * *'  # Her 6 saatte bir çalışır
  workflow_dispatch:

jobs:
  update-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate random key and update file
        run: |
          KEY=$(cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 10)
          echo "VexonHub_$KEY" > key.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add key.txt
          git commit -m "Auto update VexonHub key"
          git push
